#! /usr/bin/env python
# -*- python -*-

"""Read the dictionary into a Bloom filter and save the filter
state for quick loading later."""

import gzip, cPickle
import bloom

bf = bloom.optimalBloom (0.05, 479000)
bf.fillwords ()
cPickle.dump (bf, gzip.GzipFile ('dictbf.dat.gz', 'wb', 9))
