#! /usr/bin/env python
# -*- python -*-

"""Prints out whether words might be in the dictionary or not."""

import sys, cPickle
import bloom

wordstocheck = sys.argv[1:]

# Load up our special data structure. cPickle loads up a preexisting
# BloomFilter object from disk and returns it to us. The class is
# implemented in bloom.py.
bf = cPickle.load (file ('dictbf.dat'))

# Compute the false-positive rate of the filter.
# FIXME: do something useful with this number?
fp = bf.fprate ()

for word in wordstocheck:
    if bf.maycontain (word):
        print word, 'MIGHT BE in the dictionary'
    else:
        print word, 'is DEFINITELY NOT in the dictionary'
